"""
Unit tests for rotational constants functionality.

Covers:
- calc_moments_of_inertia()
- calc_rotor_type()
- calc_rotational_constants()
- PrincipalMoments.rotor_type()
- PrincipalMoments.__str__()
- RotationalConstants.get_in_wavenumbers()
- RotationalConstants.__str__()
- moment_to_mhz() and mhz_to_wavenumber()
- All RotorType classifications
- Edge cases: empty structure, all-zero masses, mass overrides, unknown elements
"""

import numpy as np
import pytest

from opi.input.structures.atom import Atom, PointCharge
from opi.input.structures.coordinates import Coordinates
from opi.input.structures.structure import Structure
from opi.utils.element import Element
from opi.utils.rotconst import (
    RotationalConstants,
    RotorType,
    mhz_to_wavenumber,
    moment_to_mhz,
)

# ============================================================
# Helpers
# ============================================================


def make_atom(element: str, x: float, y: float, z: float, mass: float | None = None) -> Atom:
    return Atom(
        element=Element(element),
        coordinates=Coordinates(coordinates=(x, y, z)),
        mass=mass,
    )


def make_no_real_atoms_structure() -> Structure:
    """Structure containing only a PointCharge — no real Atom instances."""
    return Structure(
        atoms=[PointCharge(coordinates=Coordinates(coordinates=(0.0, 0.0, 0.0)), charge=1.0)]
    )


# ============================================================
# Fixtures
# ============================================================


@pytest.fixture()
def water() -> Structure:
    """H2O — asymmetric top."""
    return Structure.from_xyz_block(
        "3\n\n"
        "O   0.000000   0.000000   0.119748\n"
        "H   0.000000   0.756950  -0.478993\n"
        "H   0.000000  -0.756950  -0.478993"
    )


@pytest.fixture()
def co2() -> Structure:
    """
    CO2 — linear molecule aligned exactly on Z.
    After COM shift, both O atoms lie on the Z axis so Ia = 0 exactly.
    """
    return Structure.from_xyz_block(
        "3\n\n"
        "C   0.000000   0.000000   0.000000\n"
        "O   0.000000   0.000000   1.160000\n"
        "O   0.000000   0.000000  -1.160000"
    )


@pytest.fixture()
def hcl() -> Structure:
    """HCl — guaranteed linear (diatomic), Ia = 0 exactly on Z axis."""
    return Structure.from_xyz_block(
        "2\n\nH    0.000000   0.000000   0.000000\nCl   0.000000   0.000000   1.274500"
    )


@pytest.fixture()
def methane() -> Structure:
    """CH4 — spherical top."""
    d = 0.6276
    return Structure.from_xyz_block(
        f"5\n\n"
        f"C   0.000   0.000   0.000\n"
        f"H   {d}     {d}     {d}\n"
        f"H  -{d}    -{d}     {d}\n"
        f"H  -{d}     {d}    -{d}\n"
        f"H   {d}    -{d}    -{d}"
    )


@pytest.fixture()
def benzene() -> Structure:
    """C6H6 — oblate symmetric top. Avogadro optimized geometry."""
    return Structure.from_xyz_block(
        "12\n"
        "XYZ file generated by Avogadro.\n"
        "C    -4.0132333739   3.1874756422   0.0000029092\n"
        "C    -3.7419050401   1.8193724296   0.0000182442\n"
        "H    -0.3432332788   1.9395893312   0.0002037711\n"
        "C    -2.9641082474   4.1065582543   0.0000491840\n"
        "C    -2.4213601440   1.3702446325   0.0000859970\n"
        "H    -5.0421713998   3.5372885217  -0.0000468671\n"
        "C    -1.6435439604   3.6575023283   0.0001222947\n"
        "H    -3.1755373879   5.1725212691   0.0000321721\n"
        "C    -1.3721905089   2.2894069399   0.0001431310\n"
        "H    -4.5593921780   1.1033282205  -0.0000191331\n"
        "H    -0.8260945740   4.3735825219   0.0001644962\n"
        "H    -2.2100493877   0.3043042675   0.0000939114"
    )


@pytest.fixture()
def single_atom() -> Structure:
    """Single atom — monoatomic."""
    return Structure.from_xyz_block("1\n\nC   0.000000   0.000000   0.000000")


@pytest.fixture()
def ammonia() -> Structure:
    """NH3 — oblate symmetric top (C3v). XTB2 optimized geometry."""
    return Structure.from_xyz_block(
        "4\n\n"
        "N  -0.000000  -0.000066   0.100407\n"
        "H   0.000000   0.943825  -0.266468\n"
        "H   0.817493  -0.471879  -0.266439\n"
        "H  -0.817493  -0.471879  -0.266439"
    )


@pytest.fixture()
def ch3cl() -> Structure:
    """CH3Cl — prolate symmetric top (C3v). XTB2 optimized geometry."""
    return Structure.from_xyz_block(
        "5\n\n"
        "Cl   0.975483   0.092122  -0.023926\n"
        "C    2.742455   0.092130  -0.023935\n"
        "H    3.099496   0.323883   0.981897\n"
        "H    3.099492  -0.894823  -0.326157\n"
        "H    3.099475   0.847338  -0.727561"
    )


# ============================================================
# moment_to_mhz and mhz_to_wavenumber
# ============================================================


@pytest.mark.unit
class TestHelperFunctions:
    def test_moment_to_mhz_none_input(self):
        assert moment_to_mhz(None) is None

    def test_moment_to_mhz_zero(self):
        assert moment_to_mhz(0.0) is None

    def test_moment_to_mhz_below_threshold(self):
        assert moment_to_mhz(1e-7) is None

    def test_moment_to_mhz_positive(self):
        result = moment_to_mhz(100.0)
        assert result is not None
        assert result > 0.0

    def test_moment_to_mhz_known_value(self):
        # For water Ib ≈ 1.022 amu·Å² → B ≈ 435000 MHz (rough check)
        result = moment_to_mhz(1.022)
        assert result is not None
        assert 400_000 < result < 500_000

    def test_mhz_to_wavenumber_none(self):
        assert mhz_to_wavenumber(None) is None

    def test_mhz_to_wavenumber_positive(self):
        result = mhz_to_wavenumber(100_000.0)
        assert result is not None
        assert result > 0.0

    def test_mhz_to_wavenumber_proportional(self):
        a = mhz_to_wavenumber(100.0)
        b = mhz_to_wavenumber(200.0)
        assert a is not None and b is not None
        assert pytest.approx(b, rel=1e-9) == 2 * a


# ============================================================
# PrincipalMoments
# ============================================================


@pytest.mark.unit
class TestPrincipalMoments:
    def test_rotor_type_monoatomic(self, single_atom):
        pm = single_atom.calc_moments_of_inertia()
        assert pm is not None
        assert pm.rotor_type() == RotorType.MONOATOMIC

    def test_rotor_type_linear(self, hcl):
        pm = hcl.calc_moments_of_inertia()
        assert pm is not None
        assert pm.rotor_type() == RotorType.LINEAR

    def test_rotor_type_spherical_top(self, methane):
        pm = methane.calc_moments_of_inertia()
        assert pm is not None
        assert pm.rotor_type() == RotorType.SPHERICAL_TOP

    def test_rotor_type_oblate_top(self, benzene):
        pm = benzene.calc_moments_of_inertia()
        assert pm is not None
        assert pm.rotor_type() == RotorType.OBLATE_TOP

    def test_rotor_type_oblate_top_ammonia(self, ammonia):
        pm = ammonia.calc_moments_of_inertia()
        assert pm is not None
        assert pm.rotor_type() == RotorType.OBLATE_TOP

    def test_rotor_type_prolate_top(self, ch3cl):
        pm = ch3cl.calc_moments_of_inertia()
        assert pm is not None
        assert pm.rotor_type() == RotorType.PROLATE_TOP

    def test_rotor_type_asymmetric_top(self, water):
        pm = water.calc_moments_of_inertia()
        assert pm is not None
        assert pm.rotor_type() == RotorType.ASYMMETRIC_TOP

    def test_moments_sorted_ascending(self, water):
        pm = water.calc_moments_of_inertia()
        assert pm is not None
        assert pm.Ia <= pm.Ib <= pm.Ic

    def test_axes_shape(self, water):
        pm = water.calc_moments_of_inertia()
        assert pm is not None
        assert pm.axes.shape == (3, 3)

    def test_axes_orthonormal(self, water):
        pm = water.calc_moments_of_inertia()
        assert pm is not None
        product = pm.axes.T @ pm.axes
        np.testing.assert_allclose(product, np.eye(3), atol=1e-10)

    def test_str_output(self, water):
        """str(PrincipalMoments) should match the expected formatted output exactly."""
        pm = water.calc_moments_of_inertia()
        assert pm is not None
        assert str(pm) == (
            "Moments of inertia (amu·Å²):\n  Ia = 0.641840\n  Ib = 1.155114\n  Ic = 1.796955"
        )


# ============================================================
# calc_moments_of_inertia
# ============================================================


@pytest.mark.unit
class TestCalcMomentsOfInertia:
    def test_returns_none_for_empty_structure(self):
        assert make_no_real_atoms_structure().calc_moments_of_inertia() is None

    def test_returns_none_for_all_zero_masses(self, water):
        """Setting mass=0.0 on all atoms should return None."""
        for atom in water.real_atoms:
            atom.mass = 0.0
        assert water.calc_moments_of_inertia() is None

    def test_ghost_atoms_ignored(self):
        """PointCharge should not contribute to moments."""
        real = Structure.from_xyz_block(
            "3\n\n"
            "O   0.000000   0.000000   0.119748\n"
            "H   0.000000   0.756950  -0.478993\n"
            "H   0.000000  -0.756950  -0.478993"
        )
        with_pc = Structure(
            atoms=[
                Atom(
                    element=Element("O"), coordinates=Coordinates(coordinates=(0.0, 0.0, 0.119748))
                ),
                Atom(
                    element=Element("H"),
                    coordinates=Coordinates(coordinates=(0.0, 0.756950, -0.478993)),
                ),
                Atom(
                    element=Element("H"),
                    coordinates=Coordinates(coordinates=(0.0, -0.756950, -0.478993)),
                ),
                PointCharge(coordinates=Coordinates(coordinates=(5.0, 5.0, 5.0)), charge=1.0),
            ]
        )
        pm_real = real.calc_moments_of_inertia()
        pm_pc = with_pc.calc_moments_of_inertia()
        assert pm_real is not None and pm_pc is not None
        assert pytest.approx(pm_real.Ia, rel=1e-6) == pm_pc.Ia
        assert pytest.approx(pm_real.Ib, rel=1e-6) == pm_pc.Ib
        assert pytest.approx(pm_real.Ic, rel=1e-6) == pm_pc.Ic

    def test_atom_mass_override(self, water):
        """Setting `atom.mass` directly should change the moments."""
        pm_default = water.calc_moments_of_inertia()
        water.real_atoms[0].mass = 17.999  # override O mass
        pm_custom = water.calc_moments_of_inertia()
        assert pm_default is not None and pm_custom is not None
        assert pm_default.Ic != pytest.approx(pm_custom.Ic, rel=1e-3)

    def test_elem_masses_override(self, water):
        """Per-element override via `elem_masses` should change the moments."""
        pm_default = water.calc_moments_of_inertia()
        pm_elem = water.calc_moments_of_inertia(elem_masses={"H": 2.014})
        assert pm_default is not None and pm_elem is not None
        assert pm_default.Ic != pytest.approx(pm_elem.Ic, rel=1e-3)

    def test_atom_mass_priority_over_elem_masses(self, water):
        """`atom.mass` should take priority over `elem_masses` for the same atom."""
        water.real_atoms[0].mass = 17.999
        pm_atom_mass = water.calc_moments_of_inertia()
        pm_elem = water.calc_moments_of_inertia(elem_masses={"O": 16.0})
        assert pm_atom_mass is not None and pm_elem is not None
        # atom.mass wins, so specifying elem_masses for O should NOT change the result
        assert pytest.approx(pm_atom_mass.Ic, rel=1e-9) == pm_elem.Ic

    def test_zero_mass_atoms_filtered(self, water):
        """Atoms with zero mass are excluded; remaining atoms determine the rotor type."""
        # Set H masses to 0 — only O remains → monoatomic
        water.real_atoms[1].mass = 0.0
        water.real_atoms[2].mass = 0.0
        pm = water.calc_moments_of_inertia()
        assert pm is not None
        assert pm.rotor_type() == RotorType.MONOATOMIC

    def test_water_moments_known_values(self, water):
        """
        Check moments are self-consistent: Ia <= Ib <= Ic and all positive.
        We verify internal consistency and a physically reasonable range
        rather than absolute values.
        """
        pm = water.calc_moments_of_inertia()
        assert pm is not None
        assert pm.Ia > 0.0
        assert pm.Ia <= pm.Ib <= pm.Ic
        assert 0.1 < pm.Ia < 5.0
        assert 0.1 < pm.Ib < 5.0
        assert 0.1 < pm.Ic < 5.0


# ============================================================
# calc_rotor_type
# ============================================================


@pytest.mark.unit
class TestCalcRotorType:
    def test_with_precomputed_moments(self, water):
        pm = water.calc_moments_of_inertia()
        assert water.calc_rotor_type(moments=pm) == RotorType.ASYMMETRIC_TOP

    def test_without_precomputed_moments(self, water):
        assert water.calc_rotor_type() == RotorType.ASYMMETRIC_TOP

    def test_returns_none_for_empty_structure(self):
        assert make_no_real_atoms_structure().calc_rotor_type() is None

    def test_all_rotor_types(self, single_atom, hcl, methane, benzene, ammonia, ch3cl, water):
        assert single_atom.calc_rotor_type() == RotorType.MONOATOMIC
        assert hcl.calc_rotor_type() == RotorType.LINEAR
        assert methane.calc_rotor_type() == RotorType.SPHERICAL_TOP
        assert benzene.calc_rotor_type() == RotorType.OBLATE_TOP
        assert ammonia.calc_rotor_type() == RotorType.OBLATE_TOP
        assert ch3cl.calc_rotor_type() == RotorType.PROLATE_TOP
        assert water.calc_rotor_type() == RotorType.ASYMMETRIC_TOP


# ============================================================
# calc_rotational_constants
# ============================================================


@pytest.mark.unit
class TestCalcRotationalConstants:
    def test_returns_none_for_empty_structure(self):
        assert make_no_real_atoms_structure().calc_rotational_constants() is None

    def test_returns_rotational_constants(self, water):
        rc = water.calc_rotational_constants()
        assert rc is not None
        assert isinstance(rc, RotationalConstants)

    def test_abc_ordering(self, water):
        """A ≥ B ≥ C by convention (ascending moments → descending constants)."""
        rc = water.calc_rotational_constants()
        assert rc is not None
        assert rc.A is not None and rc.B is not None and rc.C is not None
        assert rc.A >= rc.B >= rc.C

    def test_linear_molecule_has_none_constants(self, hcl):
        """HCl is linear: Ia = 0, so A should be None."""
        rc = hcl.calc_rotational_constants()
        assert rc is not None
        assert rc.A is None

    def test_monoatomic_all_none(self, single_atom):
        rc = single_atom.calc_rotational_constants()
        assert rc is not None
        assert rc.A is None
        assert rc.B is None
        assert rc.C is None

    def test_get_in_wavenumbers_returns_tuple(self, water):
        rc = water.calc_rotational_constants()
        assert rc is not None
        wn = rc.get_in_wavenumbers()
        assert isinstance(wn, tuple)
        assert len(wn) == 3

    def test_get_in_wavenumbers_none_propagates(self, hcl):
        rc = hcl.calc_rotational_constants()
        assert rc is not None
        wn = rc.get_in_wavenumbers()
        assert wn[0] is None  # A is None for linear

    def test_get_in_wavenumbers_values_positive(self, water):
        rc = water.calc_rotational_constants()
        assert rc is not None
        wn = rc.get_in_wavenumbers()
        assert all(v is not None and v > 0 for v in wn)

    def test_get_in_wavenumbers_consistent_with_mhz(self, water):
        """Manual conversion should match get_in_wavenumbers."""
        rc = water.calc_rotational_constants()
        assert rc is not None
        wn = rc.get_in_wavenumbers()
        assert wn[0] is not None and rc.A is not None
        assert pytest.approx(wn[0], rel=1e-9) == mhz_to_wavenumber(rc.A)

    def test_str_output(self, water):
        """str(RotationalConstants) should match the expected formatted output exactly."""
        rc = water.calc_rotational_constants()
        assert rc is not None
        assert str(rc) == (
            "Rotational constants:\n"
            "  A = 787390.377635 MHz   (26.264516 cm⁻¹)\n"
            "  B = 437514.333074 MHz   (14.593907 cm⁻¹)\n"
            "  C = 281241.939008 MHz   (9.381221 cm⁻¹)"
        )

    def test_a_not_in_sync_problem(self, water):
        """
        Mutating rc.A should NOT affect get_in_wavenumbers,
        since wavenumbers are computed on the fly.
        """
        rc = water.calc_rotational_constants()
        assert rc is not None
        wn_before = rc.get_in_wavenumbers()[0]
        rc.A = rc.A * 5 if rc.A is not None else None  # type: ignore[operator]
        wn_after = rc.get_in_wavenumbers()[0]
        assert wn_before != wn_after

    def test_elem_masses_forwarded(self, water):
        """elem_masses passed to calc_rotational_constants should affect the result."""
        rc_default = water.calc_rotational_constants()
        rc_deuterated = water.calc_rotational_constants(elem_masses={"H": 2.014})
        assert rc_default is not None and rc_deuterated is not None
        assert rc_default.C != pytest.approx(rc_deuterated.C, rel=1e-3)
